complexity:
  TooManyFunctions:
    thresholdInClasses: 20
    
exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
    
style:
  MaxLineLength:
    excludeCommentStatements: true
